name: foundation
description: Foundation package.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  i18next: ^0.6.1
  intl: ^0.19.0
  flutter:
    sdk: flutter
  go_router: ^10.1.2


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
